language: php

php:
  - 8.1
  - 8.2
  - 8.3
  - 8.4

addons:
  code_climate:
    repo_token: e43f1f89afb5a2f6acfaea42a6a9ebd8d33538208fafa8636826c173b3f7ec26 

script:
  - vendor/bin/phpunit

before_script:
  - composer self-update
  - composer install

after_script:
  - vendor/bin/test-reporter
